github_url = "https://github.com/your-tools/lockdiff/"

[version]
current = "2.0.1"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "Cargo.toml"

[[before_commit]]
name = "Re-generate Cargo.lock and run tests"
cmd = "cargo test"

[[after_push]]
name = "publish"
cmd = "cargo publish"
