#[cfg(test)]
mod tests {
    use crate::{parse_toml_lock, Package};

    #[test]
    fn test_parse_cargo_lock() {
        let contents = r#"
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "anyhow"
version = "1.0.58"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "lockdiff"
version = "1.0.0"
dependencies = [
 "anyhow",
]"#;
        let packages = parse_toml_lock(contents).unwrap();
        assert_eq!(
            &packages,
            &[
                Package::new("anyhow", "1.0.58"),
                Package::new("lockdiff", "1.0.0")
            ]
        );
    }
}
